version: '3.8'

services:
  app:
    # image: ghcr.io/ruanspijkerman/nsarg_template:latest
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
